//for adding data
$(document).ready(function(){
    
    $('#bOA').click(function(){
        $('#OA,#OA1').show();
        $('#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR,#OA2,#OA3,#OA4').hide();
    });
    $('#bOA1').click(function(){
        $('#OA,#OA2').show();
        $('#OA1,#OA3,#OA4').hide();
    });
    $('#bOA2').click(function(){
        $('#OA,#OA3').show();
        $('#OA1,#OA2,#OA4').hide();
    });
    $('#pack').click(function(){
        $('#pack1,#OA,#OA3').show();
        $('#pack2').hide();
    });
    $('#nonpack').click(function(){
        $('#pack2,#OA,#OA3').show();
        $('#pack1,#OA1,#OA2,#OA4').hide();
    });
    $('#bOA3').click(function(){
        $('#OA,#OA4').show();
        $('#OA1,#OA2,#OA3').hide();
    });
    $('#brOA2').click(function(){
        $('#OA,#OA1').show();
        $('#OA2,#OA3,#OA4').hide();
    });
    $('#brOA3').click(function(){
        $('#OA,#OA2').show();
        $('#OA1,#OA3,#OA4').hide();
    });
    $('#brOA4').click(function(){
        $('#OA,#OA3').show();
        $('#OA1,#OA2,#OA4').hide();
    });
    $('#bOV').click(function(){
        $('#OV').show();
        $('#OA,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bOU,#OA11').click(function(){
        $('#OU').show();
        $('#OA,#OV,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bOR').click(function(){
        $('#OR').show();
        $('#OA,#OV,#OU,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    //Item
    $('#bIA').click(function(){
        $('#IA').show();
        $('#OA,#OV,#OU,#OR,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bIV').click(function(){
        $('#IV').show();
        $('#OA,#OV,#OU,#OR,#IA,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bIU').click(function(){
        $('#IU').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bIR').click(function(){
        $('#IR').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    //Workers
    $('#bWA').click(function(){
        $('#WA').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WV,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bWV').click(function(){
        $('#WV').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WU,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bWU').click(function(){
        $('#WU').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WR,#IPA,#IPV,#IPU,#IPR').hide();
    });
    $('#bWR').click(function(){
        $('#WR').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#IPA,#IPV,#IPU,#IPR').hide();
    });
    //Item Part
    $('#bIPA').click(function(){
        $('#IPA').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPV,#IPU,#IPR').hide();
    });
    $('#bIPV').click(function(){
        $('#IPV').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPU,#IPR').hide();
    });
    $('#bIPU').click(function(){
        $('#IPU').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPR').hide();
    });
    $('#bIPR').click(function(){
        $('#IPR').show();
        $('#OA,#OV,#OU,#OR,#IA,#IV,#IU,#IR,#WA,#WV,#WU,#WR,#IPA,#IPV,#IPU').hide();
    });
    $('#N').click(function(){
        $('#N1').show();
        $('#B1,#H1,#P1,#S1,#Pr1').hide();
    });
    $('#H').click(function(){
        $('#H1').show();
        $('#N1,#B1,#P1,#S1,#Pr1').hide();
    });
    $('#P').click(function(){
        $('#P1').show();
        $('#N1,#H1,#B1,#S1,#Pr1').hide();
    });
    $('#S').click(function(){
        $('#S1').show();
        $('#N1,#H1,#P1,#B1,#Pr1').hide();
    });
    $('#Pr').click(function(){
        $('#Pr1').show();
        $('#N1,#H1,#P1,#S1,#B1').hide();
    });
    //for view data
    $('#B').click(function(){
        $('#B1,#OV').show();
        $('#N1,#H1,#P1,#S1,#Pr1,#D1,#DR1').hide();
    });
    $('#N').click(function(){
        $('#N1,#OV').show();
        $('#B1,#H1,#P1,#S1,#Pr1,#D1,#DR1').hide();
    });
    $('#H').click(function(){
        $('#H1,#OV').show();
        $('#N1,#B1,#P1,#S1,#Pr1,#D1,#DR1').hide();
    });
    $('#P').click(function(){
        $('#P1,#OV').show();
        $('#N1,#H1,#B1,#S1,#Pr1,#D1,#DR1').hide();
    });
    $('#S').click(function(){
        $('#S1,#OV').show();
        $('#N1,#H1,#P1,#B1,#Pr1,#D1,#DR1').hide();
    });
    $('#Pr').click(function(){
        $('#Pr1,#OV').show();
        $('#N1,#H1,#P1,#S1,#B1,#D1,#DR1').hide();
    });
    $('#D').click(function(){
        $('#D1,#OV').show();
        $('#N1,#H1,#P1,#S1,#Pr1,#B1,#DR1').hide();
    });
    $('#DR').click(function(){
        $('#DR1,#OV').show();
        $('#N1,#H1,#P1,#S1,#Pr1,#D1,#B1').hide();
    });
});

$('#selector').change(function(){
    //$('#B1').show();
    //$('#N1,#H1,#P1,#S1,#Pr1').hide();
    alert($('#selector :selected').val());
});

